
services:

  # nest
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fincart_app
    restart: unless-stopped
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

    #    command: npm run build && npm run start:prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - fincart_network
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/health' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: fincart_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass redis_pass
      --maxmemory-policy noeviction
    volumes:
      - redis_data:/data
    networks:
      - fincart_network
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', 'redis_pass', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    restart: unless-stopped
    environment:
      REDIS_COMMANDER_KEYS_LIMIT: 1000
      REDIS_COMMANDER_STREAM_MAX_LENGTH: 1000
    ports:
      - "8882:8081"
    networks:
      - fincart_network
    depends_on:
      - redis
    volumes:
      - commander_data:/data

  # mongo
  mongodb:
    image: mongo:7-jammy
    container_name: fincart_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DOCKER_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DOCKER_MONGO_DATABASE}
    volumes:
      - mongodb_data:/data/db
    networks:
      - fincart_network
    healthcheck:
      test: [ 'CMD', 'mongosh', '--eval', "db.adminCommand('ping')" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  mongo-express:
    image: mongo-express:latest
    container_name: fincart_mongo_express
    restart: unless-stopped
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DOCKER_MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DOCKER_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - fincart_network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  commander_data:
    driver: local

networks:
  fincart_network:
    driver: bridge
    name: fincart_network