version: '3.9'

services:

  # nest
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fincart_app
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_pass
      - MONGODB_URI=mongodb://fincart:mongo_pass@mongodb:27017/fincart_events?authSource=admin
      - WEBHOOK_SECRET=my-secret-key-123

    command: npm run start:prod
    depends_on:
      redis:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - fincart_network
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:3000/health' ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: fincart_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: >
      redis-server
      --appendonly yes
      --appendfsync everysec
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
      --requirepass redis_pass
    volumes:
      - redis_data:/data
    networks:
      - fincart_network
    healthcheck:
      test: [ 'CMD', 'redis-cli', '-a', 'redis_pass', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # mongo
  mongodb:
    image: mongo:7-jammy
    container_name: fincart_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: fincart
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
      MONGO_INITDB_DATABASE: fincart_events
    volumes:
      - mongodb_data:/data/db
    networks:
      - fincart_network
    healthcheck:
      test: [ 'CMD', 'mongosh', '--eval', "db.adminCommand('ping')" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  mongo-express:
    image: mongo-express:latest
    container_name: fincart_mongo_express
    restart: unless-stopped
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: fincart
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_pass
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - fincart_network

volumes:
  redis_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  fincart_network:
    driver: bridge
    name: fincart_network